CREATE TABLE go_rabbit_pg (
	"id" VARCHAR(10) PRIMARY KEY NOT NULL,
	"title" TEXT NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL
);
