CREATE TABLE go_rabbit_pg (
	"id" TEXT PRIMARY KEY NOT NULL,
	"title" TEXT NOT NULL,
	"category" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL
);
